server:
  port: 8069

spring:
  application:
    name: currencies-server
  profiles:
    active: development
  datasource:
    platform: postgres
    continue-on-error: true
#    url: jdbc:postgresql://currencies_db:5432/currenciesDb
#    username: currenciesUser
#    password: currenciesPasswd
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
